# Generated by Django 5.1 on 2024-08-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_costumer_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Custumer',
        ),
    ]
